version: '3.8'

services:
 mariadb:
  container_name: mariadb
  build:
   context: requirements/mariadb
   args:
    - WP_DB
    - WP_USER
    - WP_PASSWORD
  image: mariadb
  restart: always
  env_file:
   - .env
  networks:
   - inception_network
  volumes:
   - mariadb_volume:/var/lib/mysql

 wordpress:
  container_name: wordpress
  build:
   context: requirements/wordpress
   args:
    - WP_DB
    - WP_USER
    - WP_PASSWORD
  image: wordpress
  restart: always
  env_file:
   - .env
  networks:
   - inception_network
  volumes:
   - wordpress_volume:/var/www/html 
  depends_on:
   - mariadb

 nginx:
  container_name: nginx
  build:
   context: requirements/nginx
  image: nginx
  restart: always
  networks:
   - inception_network
  depends_on:
   - wordpress

networks:
 inception_network:
  driver: bridge

volumes:
 mariadb_volume:
  driver_opts:
   o: bind
   type: none
   device: ${VOLUME_PATH}/mariadb
 wordpress_volume:
  driver_opts:
   o: bind
   type: none
   device: ${VOLUME_PATH}/wordpress
